package graph

import (
	"fmt"
	"strings"
	"time"
)

// RecommendationActuationRequest records one action generated from an insight/recommendation.
type RecommendationActuationRequest struct {
	ID               string         `json:"id,omitempty"`
	RecommendationID string         `json:"recommendation_id,omitempty"`
	InsightType      string         `json:"insight_type,omitempty"`
	Title            string         `json:"title"`
	Summary          string         `json:"summary,omitempty"`
	DecisionID       string         `json:"decision_id,omitempty"`
	TargetIDs        []string       `json:"target_ids,omitempty"`
	SourceSystem     string         `json:"source_system,omitempty"`
	SourceEventID    string         `json:"source_event_id,omitempty"`
	ObservedAt       time.Time      `json:"observed_at,omitempty"`
	ValidFrom        time.Time      `json:"valid_from,omitempty"`
	ValidTo          *time.Time     `json:"valid_to,omitempty"`
	Confidence       float64        `json:"confidence,omitempty"`
	AutoGenerated    bool           `json:"auto_generated,omitempty"`
	Metadata         map[string]any `json:"metadata,omitempty"`
}

// RecommendationActuationResult summarizes one action write-back operation.
type RecommendationActuationResult struct {
	ActionID         string `json:"action_id"`
	DecisionLinked   bool   `json:"decision_linked"`
	TargetsLinked    int    `json:"targets_linked"`
	SourceSystem     string `json:"source_system"`
	SourceEventID    string `json:"source_event_id"`
	RecommendationID string `json:"recommendation_id,omitempty"`
}

// ActuateRecommendation writes one action node and links it to targets and optional decision context.
func ActuateRecommendation(g *Graph, req RecommendationActuationRequest) (RecommendationActuationResult, error) {
	if g == nil {
		return RecommendationActuationResult{}, fmt.Errorf("graph is required")
	}

	req.Title = strings.TrimSpace(req.Title)
	req.RecommendationID = strings.TrimSpace(req.RecommendationID)
	req.InsightType = strings.TrimSpace(req.InsightType)
	req.Summary = strings.TrimSpace(req.Summary)
	req.DecisionID = strings.TrimSpace(req.DecisionID)
	req.SourceSystem = strings.ToLower(strings.TrimSpace(req.SourceSystem))
	req.SourceEventID = strings.TrimSpace(req.SourceEventID)
	if req.Title == "" {
		req.Title = firstNonEmpty(req.RecommendationID, req.InsightType)
	}
	if req.Title == "" {
		return RecommendationActuationResult{}, fmt.Errorf("title, recommendation_id, or insight_type is required")
	}
	if req.ObservedAt.IsZero() {
		req.ObservedAt = time.Now().UTC()
	}
	req.ObservedAt = req.ObservedAt.UTC()
	if req.ValidFrom.IsZero() {
		req.ValidFrom = req.ObservedAt
	}
	req.ValidFrom = req.ValidFrom.UTC()
	if req.SourceSystem == "" {
		req.SourceSystem = "agent"
	}
	if req.SourceEventID == "" {
		req.SourceEventID = fmt.Sprintf("actuation:%d", req.ObservedAt.UnixNano())
	}
	if req.Confidence <= 0 {
		req.Confidence = 0.80
	}
	if req.Confidence > 1 {
		req.Confidence = 1
	}

	targetIDs := uniqueActuationIDs(req.TargetIDs)
	for _, targetID := range targetIDs {
		if _, ok := g.GetNode(targetID); !ok {
			return RecommendationActuationResult{}, fmt.Errorf("target not found: %s", targetID)
		}
	}

	if req.DecisionID != "" {
		node, ok := g.GetNode(req.DecisionID)
		if !ok || node == nil {
			return RecommendationActuationResult{}, fmt.Errorf("decision not found: %s", req.DecisionID)
		}
		if node.Kind != NodeKindDecision {
			return RecommendationActuationResult{}, fmt.Errorf("node %s is not a decision", req.DecisionID)
		}
	}

	actionID := strings.TrimSpace(req.ID)
	if actionID == "" {
		actionID = fmt.Sprintf("action:actuation:%d", req.ObservedAt.UnixNano())
	}
	props := cloneAnyMap(req.Metadata)
	if props == nil {
		props = make(map[string]any)
	}
	props["action_type"] = "recommendation_actuation"
	props["status"] = firstNonEmpty(identityAnyToString(props["status"]), "planned")
	props["recommendation_id"] = req.RecommendationID
	props["insight_type"] = req.InsightType
	props["summary"] = req.Summary
	props["auto_generated"] = req.AutoGenerated
	props["source_system"] = req.SourceSystem
	props["source_event_id"] = req.SourceEventID
	props["observed_at"] = req.ObservedAt.Format(time.RFC3339)
	props["valid_from"] = req.ValidFrom.Format(time.RFC3339)
	props["confidence"] = req.Confidence
	if req.ValidTo != nil && !req.ValidTo.IsZero() {
		validTo := req.ValidTo.UTC()
		props["valid_to"] = validTo.Format(time.RFC3339)
	}

	g.AddNode(&Node{
		ID:         actionID,
		Kind:       NodeKindAction,
		Name:       req.Title,
		Provider:   req.SourceSystem,
		Properties: props,
		Risk:       RiskNone,
	})

	for _, targetID := range targetIDs {
		g.AddEdge(&Edge{
			ID:     fmt.Sprintf("%s->%s:%s", actionID, targetID, EdgeKindTargets),
			Source: actionID,
			Target: targetID,
			Kind:   EdgeKindTargets,
			Effect: EdgeEffectAllow,
			Properties: map[string]any{
				"source_system":   req.SourceSystem,
				"source_event_id": req.SourceEventID,
				"observed_at":     req.ObservedAt.Format(time.RFC3339),
				"valid_from":      req.ValidFrom.Format(time.RFC3339),
				"confidence":      req.Confidence,
			},
			Risk: RiskNone,
		})
	}

	decisionLinked := false
	if req.DecisionID != "" {
		g.AddEdge(&Edge{
			ID:     fmt.Sprintf("%s->%s:%s", req.DecisionID, actionID, EdgeKindExecutedBy),
			Source: req.DecisionID,
			Target: actionID,
			Kind:   EdgeKindExecutedBy,
			Effect: EdgeEffectAllow,
			Properties: map[string]any{
				"source_system":   req.SourceSystem,
				"source_event_id": req.SourceEventID,
				"observed_at":     req.ObservedAt.Format(time.RFC3339),
				"valid_from":      req.ValidFrom.Format(time.RFC3339),
				"confidence":      req.Confidence,
			},
			Risk: RiskNone,
		})
		decisionLinked = true
	}

	return RecommendationActuationResult{
		ActionID:         actionID,
		DecisionLinked:   decisionLinked,
		TargetsLinked:    len(targetIDs),
		SourceSystem:     req.SourceSystem,
		SourceEventID:    req.SourceEventID,
		RecommendationID: req.RecommendationID,
	}, nil
}

func uniqueActuationIDs(values []string) []string {
	if len(values) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(values))
	out := make([]string, 0, len(values))
	for _, value := range values {
		normalized := strings.TrimSpace(value)
		if normalized == "" {
			continue
		}
		if _, ok := seen[normalized]; ok {
			continue
		}
		seen[normalized] = struct{}{}
		out = append(out, normalized)
	}
	return out
}
